# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "/"
#  weight = 10

[[main]]
  name = "News"
  url = "post"
  weight = 20

[[main]]
  name = "People"
  url = "people"
  weight = 30

[[main]]
  name = "Projects"
  url = "#"
  weight = 40
[[main]]
  parent = "Projects"
  name = "Identifier Names"
  url = "project/identifier-names"
  weight = 10
[[main]]
  parent = "Projects"
  name = "Identifier Renames"
  url = "project/identifier-renames"
  weight = 20
[[main]]
  parent = "Projects"
  name = "Test Smells"
  url = "project/test-smells"
  weight = 30

[[main]]
  name = "Publications"
  url = "publication"
  weight = 50

[[main]]
  name = "Contact"
  url = "contact"
  weight = 60
